### ISSUE TITLE
Test failure in release 0.2.0 (r69544)

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-swe-nor#1]
https://bugs.debian.org/895506 - seems the old release of swe-nor (0.2.0 r69544) has bitrotted with newer version of tools. We can resolve this by disabling tests, but may also be an opportunity for a new release?

**Comment by unhammer** [comment]
New one at least passes, but yeah that's a pretty bad failure :-/ 

I'd love to get a release out, but should do all the scandipairs at once since lots has happened in languages/apertium-{nno,nob,swe,dan} since last time, and just releasing swe-nor will most likely break all the others.

**Comment by kartikm** [comment]
@TinoDidriksen I will disable test as of now in Debian.
