### ISSUE TITLE
Build endless loop?

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-swe-nor#2]
The step `lt-trim --match-section=regex@standard /usr/share/apertium/apertium-nno/nno.automorf.bin nor-swe.autobil.bin nno-swe.automorf.bin` pegs the CPU while gobbling up all available RAM. OOM-killer stepped in after 35 minutes and 103 GiB RAM.

**Comment by unhammer** [comment]
should be fixed in 931b22248bc39fc8bc4920a98065e2f99ab32c2b (tests still failed last night, but at least it compiled)
